name: py38_analysis

channels:
   - bioconda
   - conda-forge
dependencies:
   - conda-forge::python==3.8.2
   - conda-forge::scanpy==1.9.3
#   - conda-forge::anndata==0.8.0
   - conda-forge::leidenalg
   - conda-forge::scvi-tools
   - conda-forge::jupyter_contrib_nbextensions
   - conda-forge::mscorefonts
   - bioconda::gprofiler-official
   - pip
   - pip:
#       - scgen==2.1.0
